In [ ]:
import numpy as np

def flatten(array):
    vector = array.reshape(array.shape[0] * array.shape[1] * array.shape[2],1)
    return vector

sample = np.random.random([2, 3, 4])
print("original: ")
print(sample)
print("flattened: ")
print(flatten(sample))

original: 
[[[0.39585007 0.51546194 0.11459684 0.51753462]
  [0.46342159 0.58035724 0.84495747 0.246777  ]
  [0.83836155 0.37545734 0.59709616 0.27988044]]

 [[0.0093798  0.77533396 0.74586425 0.33540928]
  [0.78354245 0.54241253 0.01863756 0.28392854]
  [0.01198807 0.75890479 0.3657486  0.70914361]]]
flattened: 
[[0.39585007]
 [0.51546194]
 [0.11459684]
 [0.51753462]
 [0.46342159]
 [0.58035724]
 [0.84495747]
 [0.246777  ]
 [0.83836155]
 [0.37545734]
 [0.59709616]
 [0.27988044]
 [0.0093798 ]
 [0.77533396]
 [0.74586425]
 [0.33540928]
 [0.78354245]
 [0.54241253]
 [0.01863756]
 [0.28392854]
 [0.01198807]
 [0.75890479]
 [0.3657486 ]
 [0.70914361]]


In [2]:
import math

def sigmoid_math_exp(x):
    return 1 / (1 + math.exp(-x))
print(sigmoid_math_exp(10))

0.9999546021312976


In [3]:
import numpy as np

def softmax(matrix):
    exp_matrix = np.exp(matrix)

    row_sums = np.sum(exp_matrix, axis=1, keepdims=True)

    softmax_matrix = exp_matrix / row_sums

    return softmax_matrix
sample_matrix = np.array([[1.0, 2.0, 3.0],
                          [4.0, 5.0, 6.0],
                          [7.0, 8.0, 9.0]])

softmax_result = softmax(sample_matrix)

print("Original Matrix:")
print(sample_matrix)
print("\nSoftmax Result:")
print(softmax_result)

Original Matrix:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Softmax Result:
[[0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]]


In [4]:
import numpy as np

sample_matrix = np.array([[1.0, 2.0, 3.0],
                          [4.0, 5.0, 6.0],
                          [7.0, 8.0, 9.0]])

row_sums = np.sum(sample_matrix, axis=1, keepdims=True)

print(row_sums)

[[ 6.]
 [15.]
 [24.]]


In [ ]:

import time
import numpy as np

def dot_product_python_lists(vector1, vector2):
    if len(vector1) != len(vector2):
        raise ValueError("Vectors must have the same length")

    dot_product = sum(x * y for x, y in zip(vector1, vector2))
    return dot_product

def dot_product_numpy(vector1, vector2):
    dot_product = np.dot(vector1, vector2)
    return dot_product
example_vector1 = [1, 2, 3, 4, 5]
example_vector2 = [5, 4, 3, 2, 1]

start_time_python_lists = time.time()
result_python_lists = dot_product_python_lists(example_vector1, example_vector2)
end_time_python_lists = time.time()
time_taken_python_lists = end_time_python_lists - start_time_python_lists

start_time_numpy_dot = time.time()
result_numpy_dot = dot_product_numpy(np.array(example_vector1), np.array(example_vector2))
end_time_numpy_dot = time.time()
time_taken_numpy_dot = end_time_numpy_dot - start_time_numpy_dot

print("Dot Product using Python Lists:", result_python_lists)
print("Dot Product using Numpy:", result_numpy_dot)


Dot Product using Python Lists: 35
Dot Product using Numpy: 35


In [ ]:

import time
import numpy as np

def outer_product_python_lists(vector1, vector2):
    outer_product = [[x * y for y in vector2] for x in vector1]
    return outer_product

def outer_product_numpy(vector1, vector2):
    outer_product = np.outer(vector1, vector2)
    return outer_product
example_vector1 = [1, 2, 3, 4, 5]
example_vector2 = [5, 4, 3, 2, 1]

start_time_python_lists = time.time()
result_python_lists = outer_product_python_lists(example_vector1, example_vector2)
end_time_python_lists = time.time()
time_taken_python_lists = end_time_python_lists - start_time_python_lists

start_time_numpy_outer = time.time()
result_numpy_outer = outer_product_numpy(np.array(example_vector1), np.array(example_vector2))
end_time_numpy_outer = time.time()
time_taken_numpy_outer = end_time_numpy_outer - start_time_numpy_outer

print("Outer Product using Python Lists:")
print(result_python_lists)
print("Time taken with Python Lists:", time_taken_python_lists, "seconds\n")

print("Outer Product using np.outer():")
print(result_numpy_outer)
print("Time taken with np.outer():", time_taken_numpy_outer, "seconds")

Outer Product using Python Lists:
[[5, 4, 3, 2, 1], [10, 8, 6, 4, 2], [15, 12, 9, 6, 3], [20, 16, 12, 8, 4], [25, 20, 15, 10, 5]]
Time taken with Python Lists: 9.274482727050781e-05 seconds

Outer Product using np.outer():
[[ 5  4  3  2  1]
 [10  8  6  4  2]
 [15 12  9  6  3]
 [20 16 12  8  4]
 [25 20 15 10  5]]
Time taken with np.outer(): 0.00026869773864746094 seconds


In [ ]:

import numpy as np

def l1_loss_python_lists(vector1, vector2):
    if len(vector1) != len(vector2):
        raise ValueError("Vectors must have the same length")

    l1_loss = sum(abs(x - y) for x, y in zip(vector1, vector2))
    return l1_loss

def l1_loss_numpy(vector1, vector2):
    if len(vector1) != len(vector2):
        raise ValueError("Vectors must have the same length")

    l1_loss = np.sum(np.abs(np.array(vector1) - np.array(vector2)))
    return l1_loss

def l2_loss_python_lists(vector1, vector2):
    if len(vector1) != len(vector2):
        raise ValueError("Vectors must have the same length")

    l2_loss = sum((x - y)**2 for x, y in zip(vector1, vector2))
    return l2_loss**0.5

def l2_loss_numpy(vector1, vector2):
    if len(vector1) != len(vector2):
        raise ValueError("Vectors must have the same length")

    l2_loss = np.linalg.norm(np.array(vector1) - np.array(vector2))
    return l2_loss
vector1 = [1, 2, 3, 4, 5]
vector2 = [5, 4, 3, 2, 5]

l1_loss_result_python_lists = l1_loss_python_lists(vector1, vector2)
print("L1 Loss using Python Lists:", l1_loss_result_python_lists)

l1_loss_result_numpy = l1_loss_numpy(np.array(vector1), np.array(vector2))
print("L1 Loss using NumPy Arrays:", l1_loss_result_numpy)

l2_loss_result_python_lists = l2_loss_python_lists(vector1, vector2)
print("\nL2 Loss using Python Lists:", l2_loss_result_python_lists)

l2_loss_result_numpy = l2_loss_numpy(np.array(vector1), np.array(vector2))
print("L2 Loss using NumPy Arrays:", l2_loss_result_numpy)

L1 Loss using Python Lists: 8
L1 Loss using NumPy Arrays: 8

L2 Loss using Python Lists: 4.898979485566356
L2 Loss using NumPy Arrays: 4.898979485566356


In [ ]:

def matrix_multiplication(vector1, vector2):
    if len(vector1) != len(vector2) or len(vector1[0]) != len(vector2[0]):
        raise ValueError("Matrices must have the same dimensions for addition")
    
    for i, j in vector1, vector2:
        placeholder = 1

In [201]:
def l1_loss(y_true, y_pred):
    return np.sum(np.abs(y_true - y_pred))

def l2_loss(y_true, y_pred):
    return np.linalg.norm(y_true - y_pred)

y_true = np.array([1,2,3,4,5])
y_pred = np.array([5,4,3,2,1])

print("L1 Loss:", l1_loss(y_true, y_pred))
print("L2 Loss:", l2_loss(y_true, y_pred))


L1 Loss: 12
L2 Loss: 6.324555320336759
