In [ ]:
import numpy as np

def flatten(array):
    vector = array.reshape(array.shape[0] * array.shape[1] * array.shape[2],1)
    return vector

sample = np.random.random([2, 3, 4])
print("original: ")
print(sample)
print("flattened: ")
print(flatten(sample))

original: 
[[[0.39585007 0.51546194 0.11459684 0.51753462]
  [0.46342159 0.58035724 0.84495747 0.246777  ]
  [0.83836155 0.37545734 0.59709616 0.27988044]]

 [[0.0093798  0.77533396 0.74586425 0.33540928]
  [0.78354245 0.54241253 0.01863756 0.28392854]
  [0.01198807 0.75890479 0.3657486  0.70914361]]]
flattened: 
[[0.39585007]
 [0.51546194]
 [0.11459684]
 [0.51753462]
 [0.46342159]
 [0.58035724]
 [0.84495747]
 [0.246777  ]
 [0.83836155]
 [0.37545734]
 [0.59709616]
 [0.27988044]
 [0.0093798 ]
 [0.77533396]
 [0.74586425]
 [0.33540928]
 [0.78354245]
 [0.54241253]
 [0.01863756]
 [0.28392854]
 [0.01198807]
 [0.75890479]
 [0.3657486 ]
 [0.70914361]]


In [2]:
import math

def sigmoid_math_exp(x):
    return 1 / (1 + math.exp(-x))
print(sigmoid_math_exp(10))

0.9999546021312976


In [3]:
import numpy as np

def softmax(matrix):
    exp_matrix = np.exp(matrix)

    row_sums = np.sum(exp_matrix, axis=1, keepdims=True)

    softmax_matrix = exp_matrix / row_sums

    return softmax_matrix
sample_matrix = np.array([[1.0, 2.0, 3.0],
                          [4.0, 5.0, 6.0],
                          [7.0, 8.0, 9.0]])

softmax_result = softmax(sample_matrix)

print("Original Matrix:")
print(sample_matrix)
print("\nSoftmax Result:")
print(softmax_result)

Original Matrix:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Softmax Result:
[[0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]]


In [4]:
import numpy as np

sample_matrix = np.array([[1.0, 2.0, 3.0],
                          [4.0, 5.0, 6.0],
                          [7.0, 8.0, 9.0]])

row_sums = np.sum(sample_matrix, axis=1, keepdims=True)

print(row_sums)

[[ 6.]
 [15.]
 [24.]]


In [ ]:

import time
import numpy as np

def dot_product_python_lists(vector1, vector2):
    if len(vector1) != len(vector2):
        raise ValueError("Vectors must have the same length")

    dot_product = sum(x * y for x, y in zip(vector1, vector2))
    return dot_product

def dot_product_numpy(vector1, vector2):
    dot_product = np.dot(vector1, vector2)
    return dot_product
example_vector1 = [1, 2, 3, 4, 5]
example_vector2 = [5, 4, 3, 2, 1]

start_time_python_lists = time.time()
result_python_lists = dot_product_python_lists(example_vector1, example_vector2)
end_time_python_lists = time.time()
time_taken_python_lists = end_time_python_lists - start_time_python_lists

start_time_numpy_dot = time.time()
result_numpy_dot = dot_product_numpy(np.array(example_vector1), np.array(example_vector2))
end_time_numpy_dot = time.time()
time_taken_numpy_dot = end_time_numpy_dot - start_time_numpy_dot

print("Dot Product using Python Lists:", result_python_lists)
print("Dot Product using Numpy:", result_numpy_dot)


Dot Product using Python Lists: 35
Dot Product using Numpy: 35


In [ ]:

import time
import numpy as np

def outer_product_python_lists(vector1, vector2):
    outer_product = [[x * y for y in vector2] for x in vector1]
    return outer_product

def outer_product_numpy(vector1, vector2):
    outer_product = np.outer(vector1, vector2)
    return outer_product
example_vector1 = [1, 2, 3, 4, 5]
example_vector2 = [5, 4, 3, 2, 1]

start_time_python_lists = time.time()
result_python_lists = outer_product_python_lists(example_vector1, example_vector2)
end_time_python_lists = time.time()
time_taken_python_lists = end_time_python_lists - start_time_python_lists

start_time_numpy_outer = time.time()
result_numpy_outer = outer_product_numpy(np.array(example_vector1), np.array(example_vector2))
end_time_numpy_outer = time.time()
time_taken_numpy_outer = end_time_numpy_outer - start_time_numpy_outer

print("Outer Product using Python Lists:")
print(result_python_lists)
print("Time taken with Python Lists:", time_taken_python_lists, "seconds\n")

print("Outer Product using np.outer():")
print(result_numpy_outer)
print("Time taken with np.outer():", time_taken_numpy_outer, "seconds")

Outer Product using Python Lists:
[[5, 4, 3, 2, 1], [10, 8, 6, 4, 2], [15, 12, 9, 6, 3], [20, 16, 12, 8, 4], [25, 20, 15, 10, 5]]
Time taken with Python Lists: 9.274482727050781e-05 seconds

Outer Product using np.outer():
[[ 5  4  3  2  1]
 [10  8  6  4  2]
 [15 12  9  6  3]
 [20 16 12  8  4]
 [25 20 15 10  5]]
Time taken with np.outer(): 0.00026869773864746094 seconds


In [ ]:

import numpy as np

def l1_loss_python_lists(vector1, vector2):
    if len(vector1) != len(vector2):
        raise ValueError("Vectors must have the same length")

    l1_loss = sum(abs(x - y) for x, y in zip(vector1, vector2))
    return l1_loss

def l1_loss_numpy(vector1, vector2):
    if len(vector1) != len(vector2):
        raise ValueError("Vectors must have the same length")

    l1_loss = np.sum(np.abs(np.array(vector1) - np.array(vector2)))
    return l1_loss

def l2_loss_python_lists(vector1, vector2):
    if len(vector1) != len(vector2):
        raise ValueError("Vectors must have the same length")

    l2_loss = sum((x - y)**2 for x, y in zip(vector1, vector2))
    return l2_loss**0.5

def l2_loss_numpy(vector1, vector2):
    if len(vector1) != len(vector2):
        raise ValueError("Vectors must have the same length")

    l2_loss = np.linalg.norm(np.array(vector1) - np.array(vector2))
    return l2_loss
vector1 = [1, 2, 3, 4, 5]
vector2 = [5, 4, 3, 2, 5]

l1_loss_result_python_lists = l1_loss_python_lists(vector1, vector2)
print("L1 Loss using Python Lists:", l1_loss_result_python_lists)

l1_loss_result_numpy = l1_loss_numpy(np.array(vector1), np.array(vector2))
print("L1 Loss using NumPy Arrays:", l1_loss_result_numpy)

l2_loss_result_python_lists = l2_loss_python_lists(vector1, vector2)
print("\nL2 Loss using Python Lists:", l2_loss_result_python_lists)

l2_loss_result_numpy = l2_loss_numpy(np.array(vector1), np.array(vector2))
print("L2 Loss using NumPy Arrays:", l2_loss_result_numpy)

L1 Loss using Python Lists: 8
L1 Loss using NumPy Arrays: 8

L2 Loss using Python Lists: 4.898979485566356
L2 Loss using NumPy Arrays: 4.898979485566356


In [201]:
def l1_loss(y_true, y_pred):
    return np.sum(np.abs(y_true - y_pred))

def l2_loss(y_true, y_pred):
    return np.linalg.norm(y_true - y_pred)

y_true = np.array([1,2,3,4,5])
y_pred = np.array([5,4,3,2,1])

print("L1 Loss:", l1_loss(y_true, y_pred))
print("L2 Loss:", l2_loss(y_true, y_pred))


L1 Loss: 12
L2 Loss: 6.324555320336759


the cell above is for reference to the cell above it

In [ ]:
import numpy as np

def matrix_addition_python(matrix1, matrix2):
    if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
        raise ValueError("Matrices must have the same dimensions for addition")

    result_matrix = [[matrix1[i][j] + matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]
    return result_matrix

def matrix_addition_numpy(matrix1, matrix2):
    if matrix1.shape != matrix2.shape:
        raise ValueError("Matrices must have the same dimensions for addition")

    result_matrix = matrix1 + matrix2
    return result_matrix
matrix1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

result_matrix_python = matrix_addition_python(matrix1, matrix2)
print("Matrix Addition using Python Lists:")
for row in result_matrix_python:
    print(row)

result_matrix_numpy = matrix_addition_numpy(np.array(matrix1), np.array(matrix2))
print("\nMatrix Addition using NumPy Arrays:")
print(result_matrix_numpy)

[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


In [ ]:
import numpy as np

def matrix_vector_multiplication_python(matrix, vector):
    if len(matrix[0]) != len(vector):
        raise ValueError("Number of columns in the matrix must be equal to the length of the vector")

    result_vector = [sum(matrix[i][j] * vector[j] for j in range(len(vector))) for i in range(len(matrix))]
    return result_vector

def matrix_vector_multiplication_numpy(matrix, vector):
    if matrix.shape[1] != len(vector):
        raise ValueError("Number of columns in the matrix must be equal to the length of the vector")

    result_vector = np.dot(matrix, vector)
    return result_vector
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
vector = [2, 3, 4]

result_vector_python = matrix_vector_multiplication_python(matrix, vector)
print("Matrix and Vector Multiplication using Python Lists:", result_vector_python)

result_vector_numpy = matrix_vector_multiplication_numpy(np.array(matrix), np.array(vector))
print("Matrix and Vector Multiplication using NumPy Arrays:", result_vector_numpy)

[20, 47, 74]


In [23]:
def matrix_multiplication_python(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        raise ValueError("Number of columns in the first matrix must be equal to the number of rows in the second matrix")

    result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(len(matrix2))) for j in range(len(matrix2[0]))] for i in range(len(matrix1))]
    return result_matrix

import numpy as np

def matrix_multiplication_numpy(matrix1, matrix2):
    if matrix1.shape[1] != matrix2.shape[0]:
        raise ValueError("Number of columns in the first matrix must be equal to the number of rows in the second matrix")

    result_matrix = np.dot(matrix1, matrix2)
    return result_matrix
matrix1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

result_matrix_python = matrix_multiplication_python(matrix1, matrix2)
print("Matrix and Matrix Multiplication using Python Lists:")
for row in result_matrix_python:
    print(row)

result_matrix_numpy = matrix_multiplication_numpy(np.array(matrix1), np.array(matrix2))
print("\nMatrix and Matrix Multiplication using NumPy Arrays:")
print(result_matrix_numpy)

Matrix and Matrix Multiplication using Python Lists:
[30, 24, 18]
[84, 69, 54]
[138, 114, 90]

Matrix and Matrix Multiplication using NumPy Arrays:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
